#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Function to show a spinner
spinner() {
  local indicators=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
  local i=0
  while :; do
    printf "\r${indicators[i]} Running... "
    sleep 0.1
    i=$(( (i+1) % ${#indicators[@]} ))
  done
}

# Start the spinner in the background
spinner & SPINNER_PID=$!

# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    kill $SPINNER_PID
    exit 1;
fi;

# rodar os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
    kill $SPINNER_PID
    exit 1;
fi;

# Stop the spinner
kill $SPINNER_PID

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;
