#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Função para exibir indicador de progresso
show_progress() {
    local current_step=$1

    # Indicadores de progresso
    local indicators=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")

    # Calcula o índice do indicador de progresso
    local index=$((current_step % ${#indicators[@]}))

    # Limpa a linha anterior
    printf "\r"

    # Exibe o indicador de progresso
    # shellcheck disable=SC2182
    printf Progresso: %s ${indicators[index]}
}

# Função para exibir indicador de conclusão
show_completion() {
    echo ""
    echo "✅ $1 concluído."
    echo ""
}

# Restante do script...

# Contador de tarefas
total_tasks=3
current_task=0

# Rodar o phpstan
show_progress $((++current_task))
echo "⌛ Executando PHPStan..."
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉"
    exit 1
fi
show_completion "PHPStan"

# rodar os testes
show_progress $((++current_task))
echo "⌛ Executando testes Laravel..."
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉"
    exit 1
fi
show_completion "Testes Laravel"

# Formatar cada arquivo alterado usando o Laravel Pint
show_progress $((++current_task))
echo "⌛ Formatando arquivos..."
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES; do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1
    git add "${FILE}"
done

show_completion "Formatação concluída"

exit 0
