#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Função para exibir barra de progresso
show_progress() {
    local total_steps=$1
    local current_step=$2
    local progress=$((current_step * 100 / total_steps))
    local bar_length=$((progress / 2))
    printf "\r[%-${bar_length}s] %d%%" "$(< /dev/zero tr '\0' ' ' | head -c $bar_length)" "$progress"
}

# Função para exibir indicador de conclusão
show_completion() {
    echo ""
    echo "✅ $1 concluído."
    echo ""
}

# Restante do script...

# Contador de tarefas
total_tasks=3
current_task=0

# Rodar o phpstan
show_progress $total_tasks $((++current_task))
echo "⌛ Executando PHPStan..."
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉"
    exit 1
fi
show_completion "PHPStan"

# rodar os testes
show_progress $total_tasks $((++current_task))
echo "⌛ Executando testes Laravel..."
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉"
    exit 1
fi
show_completion "Testes Laravel"

# Formatar cada arquivo alterado usando o Laravel Pint
show_progress $total_tasks $((++current_task))
echo "⌛ Formatando arquivos..."
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES; do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1
    git add "${FILE}"
done

show_completion "Formatação concluída"

exit 0
